|
  {
    "content" : "test",
    "title" : "test",
    "createdDate" : null,
    "updatedDate" : null,
    "_links" : {
      "self" : {
        "href" : "http://localhost:8080/news/1"
      },
      "delete" : {
        "href" : "http://localhost:8080/news/1",
        "method" : "DELETE"
      },
      "update" : {
        "href" : "http://localhost:8080/news/1",
        "method" : "PATCH"
      },
      "author" : {
        "href" : "http://localhost:8080/users/2"
      }
    }
  }