User: !include types/users/user.raml
UserLinks: !include types/users/userLinks.raml
CreatingUser: !include types/users/createUser.raml
UpdatingUser:  !include types/users/updateUser.raml
Error: !include types/errors/commonError.raml
ValidateError: !include types/errors/validateError.raml
InvalidValueError: !include types/errors/invalidValueError.raml
UserPageContainer:  !include types/users/userPage.raml
Page: !include types/pages/page.raml
PageLinks: !include types/pages/pageLinks.raml
LinkObject: !include types/common/linkObject.raml
LinkObjectWithMethod: !include types/common/linkWithMethodObject.raml
UsersEmbedded: !include types/users/usersEmbedded.raml
SelfLink: !include types/common/selfLink.raml
