uriParameters:
  id:
    type: integer
get:
  description: "Return the user with given id."
  responses:
    200: !include response/user/getUserOk.raml
    404: !include response/user/userNotFound.raml
patch:
  description: "Update the user with given id."
  body:
        application/json:
          type: UpdatingUser
  responses:
    200:
      description: "OK"
    404: !include response/user/userNotFound.raml
    422: !include response/user/userUnprocessableEntityPassword.raml
delete:
  description: "Delete the user with given id."
  responses:
    204:
       description: "No content."
    404: !include response/user/userNotFound.raml
