 |
   {
     "username" : "testUsername",
     "email" : "testEmail@mail.com",
     "_links" : {
       "self" : {
         "href" : "http://localhost:8080/users/1"
       },
       "delete" : {
         "href" : "http://localhost:8080/users/1",
         "method" : "DELETE"
       },
       "update" : {
         "href" : "http://localhost:8080/users/1",
         "method" : "PATCH"
       }
     }
   }